page/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'page'


urlpatterns = [
    url(r'^add-page/$', AddPage, name='add_page'),
    url(r'^pages/$', PagesView, name='page_list'),
    url(r'^delete-page/$', DeletePage, name='delete_page'),
    url(r'^view-page/(?P<id>[-\w]+)/$', ViewPage, name='view_page'),
    url(r'^edit-page/(?P<id>[-\w]+)/$', PageEdit, name='edit_page'),
    url(r'^change-state/(?P<id>[-\w]+)/$', ChangeState, name='change_state'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include, url
from django.conf import settings
from accounts.views import  AdminLoginView
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls', 'accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    path('backup/', include('backup.urls') , name="Back_up"),
    path('page/', include('page.urls') , name="page"),
    path('contacts/', include('contact.urls') , name="contact"),
    path('services/', include('services.urls') , name="services"),
    path('ratings/', include('ratings.urls') , name="ratings"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] 

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

templates/page/add-page.html
{% include 'admin-includes/header.html' %} {% load static %} {% block content %}


<div class="content-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h4 class="card-title">Add Pages</h4>
                    </div>
                    <div class="card-body">
                        <div class="profile-tab">
                            <div class="settings-form">
                                <form id="add-page" action="{% url 'page:add_page' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Title</label>
                                            <input id="title" type="text" placeholder="Enter Title" value="{{title}}" name="title" class="form-control form-control-lg" maxlength="254">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Type</label>
                                            <div class="select-icon position-relative">
                                                <select name="type" id="type" required class="form-control form-control-lg">
                                                    <option value="">Select</option>
                                                    <option value="1">Terms & Conditions</option>
                                                    <option value="2">Privacy Policy</option>
                                                    <option value="3">About Us</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Description</label>
                                            <textarea maxlength="1000" placeholder="Enter Description" name="content" id="editor" class="form-control form-control-lg">{{content}}</textarea>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <button class="btn btn-primary" type="submit">Save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %} {% endblock %}
<script type="text/javascript">
    $("#add-page").validate({
        rules: {
            type: {
                required: true,
            },
            title: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            content: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            }
        },
        messages: {
            type: {
                required: "Please select type of page",
            },
            title: {
                required: "Please enter title",
            },
            content: {
                required: "Please enter description"
            }
        }
    });
</script>
<script src="https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
<script>
	CKEDITOR.replace('editor');
</script>

templates/page/edit-page.html
{% include 'admin-includes/header.html' %}
{% load static %}
{% block content %}
<div class="content-body">
    <div class="container-fluid">
        
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h4 class="card-title">Update Pages</h4>
                    </div>
                    <div class="card-body">
                        <div class="profile-tab">
                            <div class="settings-form">
                                <form id="add-page"  method="POST"
                                    enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Title</label>
                                            <input type="text" placeholder="Enter Title" value="{{page.title}}"
                                                name="title" id="title" class="form-control form-control-lg" maxlength="254">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Type</label>
                                            {% if page.type_id == 2 %}
                                            <input type="text" class="form-control form-control-lg" readonly value="Privacy Policy">
                                            {% elif page.type_id == 1 %}
                                            <input type="text" class="form-control form-control-lg" readonly value="Terms & Conditions">
                                            {% elif page.type_id == 3 %}
                                            <input type="text" class="form-control form-control-lg" readonly value="About Us">
                                            {% endif %}
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Description</label>
                                            <textarea maxlength="1000" placeholder="Enter Description" id="editor" name="content"
                                                class="form-control form-control-lg">{{page.content }}</textarea>
                                        </div>
                                        <input type="text" class="form-control" name="page_id" value="{{page.id}}"
                                            hidden>
                                        <div class="form-group col-md-12">
                                            <button class="btn btn-primary" type="submit">Update</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %}
{% endblock %}
<script src="https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
<script>
	CKEDITOR.replace('editor');
</script>

<script type="text/javascript">
    $("#add-page").validate({
        rules: {
            title: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            content: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            }
        },
        messages: {
            title: {
                required: "Please enter title",
            },
            content: {
                required: "Please enter description"
            }
        }
    });
</script>

templates/page/page.html
{% include 'admin-includes/header.html' %}
{% load static %}
{% block content %}		

<div class="content-body">
    <!-- row -->
    <div class="container-fluid">	
        <div class="row">
            <div class="col-12">
                <div class="card card-custom">
                    <div class="card-header d-flex justify-content-between align-items-center card-header-custom">
                        <h4 class="card-title">Pages</h4>
                        <div class="addlocation">
                            <a href="{% url 'page:add_page' %}">Add<i class="far fa-plus ml-1"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form action="{% url 'page:page_list' %}" method="GET">
                                <table class="sortable table table-responsive-md ">
                                    <thead>
                                        <tr>
                                            <th><strong>Id</strong></th>
                                            <th><strong>Title</strong></th>
                                            <th><strong>Description</strong></th>
                                            <th><strong>Type</strong></th>
                                            <th><strong>Created On</strong></th>
                                            <th><strong>Action</strong></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><input style="width: 70px;" type="text" {% if id %} value="{{id}}" {% endif %} class="form-control" name="id"></td>
                                            <td><input type="text" {% if title %} value="{{title}}" {% endif %} class="form-control" name="title"></td>
                                            <td><input type="text" {% if content %} value="{{content}}" {% endif %} class="form-control" name="content"></td>
                                            <td>
                                                <select class="form-control" name="type_id" onchange="this.form.submit()">
                                                    <option  value=""></option>
                                                    <option {% if type_id == '1' %} selected {% endif %} value="1">Terms & Conditions</option>
                                                    <option {% if type_id == '2' %} selected {% endif %} value="2">Privacy Policy</option>
                                                    <option {% if type_id == '3' %} selected {% endif %} value="3">About Us</option>
                                                </select>
                                            </td>
                                            <td><input onchange="this.form.submit()" type="date" onkeydown="return false" value="{{created_on}}" class="position-relative form-control" name="created_on"></td>
                                            <td><button type="submit" class="btn btn-dark savebtn">Search</button></td>
                                        </tr>
                                    {% if pages %}
                                        {% for page in pages  %}
                                            <tr>
                                                <td>{{page.id}}</td>
                                                <td>{{page.title}}</td>
                                                <td>{{page.content | truncatechars:80 |safe}}</td>
                                                {% if page.type_id == 1 %}
                                                    <td>Terms & Conditions</td>
                                                {% elif page.type_id == 2 %}
                                                    <td>Privacy Policy</td>
                                                {% elif page.type_id == 3 %}
                                                    <td>About Us</td>
                                                {% endif %}
                                                <td>
                                                    <script>
                                                        var d = ConvertGTime("{{ page.created_on|date:'Y-m-d' }}","{{ page.created_on|time:'H:i' }}");
                                                        document.write(d);
                                                    </script>
                                                </td>
                                                <td>
                                                    <div class="d-flex">
                                                        <a href="{% url 'page:edit_page' page.id %}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-pencil"></i></a>
                                                        <a href="{% url 'page:view_page' page.id %}" class="btn btn-success shadow btn-xs sharp mr-1"><i class="fa fa-eye"></i></a>
                                                        <a data-attr="{{page.id}}" id="delete-btn" class="btn btn-danger shadow btn-xs sharp"><i class="fa fa-trash"></i></a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <td align="center" colspan="5">No Data Found</td>
                                    {% endif %}
                                    </tbody>
                                </table>
                            </form>
                            {% if pages.has_other_pages %}
							<ul class="pagination">
								{% if pages.has_previous %}
								<li><a href="?page={{ pages.previous_page_number }}">&laquo;</a></li>
								{% else %}
								<li class="disabled"><span>&laquo;</span></li>
								{% endif %}
								{% for i in pages.paginator.page_range %}
								{% if pages.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% else %}
								<li><a href="?page={{ i }}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if pages.has_next %}
								<li><a href="?page={{ pages.next_page_number }}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span>&raquo;</span></li>
								{% endif %}
							</ul>
							{% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% include 'admin-includes/footer.html' %}
<script>
    $(document).on('click', '#delete-btn', function () {
        if (confirm("Are you sure to delete this page?")) {
            var id = $(this).attr('data-attr');
            $.ajax({
                url: "{% url 'page:delete_page' %}",
                type: 'get',
                data: {
                    'id': id
                },
                success: function (result) {
                    location.reload();
                }
            });
        }
    });
</script>

templates/page/view-page.html
{% include 'admin-includes/header.html' %}
{% load static %}
{% block content %}
<div class="content-body">
   <div class="container-fluid">
      <div class="row">
         <div class="col-xl-12">
            <div class="card">
               <div class="card-body">
                  <div class="profile-tab d-flex position-relative">
                     <div class="profile-personal-info w-100">
                        <h4 class="text-primary mb-4">Page Information</h4>
                        <div class="row mb-3 mb-sm-2">
                           <div class="col-12 col-sm-4 col-lg-3">
                              <h5 class="f-w-500">Title <span class="d-none d-sm-block float-sm-right">:</span>
                              </h5>
                           </div>
                           <div class="col-12 col-sm-8 col-lg-9"><span>{{page.title}}</span>
                           </div>
                        </div>
                        <div class="row mb-3 mb-sm-2">
                           <div class="col-12 col-sm-4 col-lg-3">
                              <h5 class="f-w-500">Type <span class="d-none d-sm-block float-sm-right">:</span>
                              </h5>
                           </div>
                           {% if page.type_id == 1 %}
                           <div class="col-12 col-sm-8 col-lg-9"><span>Terms & Conditions</span>
                              {% elif page.type_id == 2 %}
                              <div class="col-12 col-sm-8 col-lg-9"><span>Privacy Policy</span>
                                 {% elif page.type_id == 3 %}
                                 <div class="col-12 col-sm-8 col-lg-9"><span>About Us</span>
                                    {% endif %}
                                    </div>
                                 </div>
                                 <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                       <h5 class="f-w-500">Created On <span class="d-none d-sm-block float-sm-right">:</span>
                                       </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9"><span>
                                          <script>
                                             var d = ConvertGTime("{{ page.created_on|date:'Y-m-d' }}", "{{ page.created_on|time:'H:i' }}");
                                             document.write(d);
                                          </script>
                                       </span>
                                    </div>
                                 </div>
                                 <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                       <h5 class="f-w-500">Description <span class="d-none d-sm-block float-sm-right">:</span></h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9"><span>{{page.content | safe }}</span>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% include 'admin-includes/footer.html' %}
{% endblock %}