accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

admin.autodiscover()

app_name = 'accounts'

urlpatterns = [
    ## Admin
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^edit-user/(?P<id>[-\w]+)/$', EditUser, name='edit_user'),
    url(r'^view/(?P<id>[-\w]+)/$',ViewUser, name='view_user'),
    url(r'^change-password/$', PasswordChange.as_view(), name='Password_Change'),

    ## Login History
    url(r'^login-history/$', LoginHistoryView, name='login_history'),
    url(r'^delete-history/$', DeleteHistory, name='delete_history'),
]

backup/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

admin.autodiscover()

app_name = 'backup'

urlpatterns = [
    url(r'^$', views.backup, name='backup'),
    url(r'^database-backup/$', views.database_backup, name='database_backup'),
    url(r'^database-schema/$', views.database_schema, name='database_schema'),
    url(r'^download-file/$', views.downloadFile, name='downloadFile'),
    url(r'^delete-backup/$', views.DeleteBackup, name='delete_backup'),
]

contact/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'contact'


urlpatterns = [
    url(r'^$', ContactsList, name='contacts_list'),
    url(r'^contacts-graph$', ContactsGraph, name='contacts_graph'),
    url(r'^contact-us/$', ContactFormView, name='contact_form'),
    url(r'^delete-contact/(?P<id>[-\w]+)/$', DeleteContact, name='delete_contact'),
    url(r'^view-contact/(?P<id>[-\w]+)/$', ViewContact, name='view_contact'),
]

page/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'page'


urlpatterns = [
    url(r'^add-page/$', AddPage, name='add_page'),
    url(r'^pages/$', PagesView, name='page_list'),
    url(r'^delete-page/$', DeletePage, name='delete_page'),
    url(r'^view-page/(?P<id>[-\w]+)/$', ViewPage, name='view_page'),
    url(r'^edit-page/(?P<id>[-\w]+)/$', PageEdit, name='edit_page'),
    url(r'^change-state/(?P<id>[-\w]+)/$', ChangeState, name='change_state'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include, url
from django.conf import settings
from accounts.views import  AdminLoginView
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls', 'accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    path('backup/', include('backup.urls') , name="Back_up"),
    path('page/', include('page.urls') , name="page"),
    path('contacts/', include('contact.urls') , name="contact"),
    path('services/', include('services.urls') , name="services"),
    path('ratings/', include('ratings.urls') , name="ratings"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] 

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

ratings/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'ratings'


urlpatterns = [
    url(r'^$', RatingReviewsList, name='ratings_list'),
    url(r'^rate-our-services/$', RateUsForm, name='rate_us'),
    url(r'^delete-review/(?P<id>[-\w]+)/$', DeleteReview, name='delete_review'),
    url(r'^view-review/(?P<id>[-\w]+)/$', ViewReview, name='view_review'),
]

templates/admin-includes/footer.html
{% load static %}
<div class="footer">
    <div class="copyright">
        <p>
          <a target="_blank" href="{% url 'frontend:privacy_policy' %}" title="Privacy Policy">Privacy Policy</a> | 
            &copy; <script>document.write(new Date().getFullYear());</script> Psychology
        </p>
    </div>
</div>
</div>
<!--*******Scripts*******-->
<!-- Required vendors -->
<script src="{% static 'admin-asset/vendor/global/global.min.js' %}"></script>
<script src="{% static 'admin-asset/js/custom.min.js' %}"></script>
<script src="{% static 'admin-asset/js/deznav-init.js' %}"></script>
<script src="{% static 'admin-asset/js/jquery.min.js' %}"></script>
<script src="{% static 'admin-asset/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'admin-asset/js/additional-methods.min.js' %}"></script>
<script>
    if ($('textarea').val()){
        $('textarea').val($('textarea').val().trim())
    }
</script>
</body>
</html>

templates/admin-includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="">
    <title>Psychology</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="" />
    <link href="{%  static 'admin-asset/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet " type="text/css" href="{% static 'admin-asset/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css" />
    <link rel="stylesheet" href="{% static 'frontend-asset/css/flash.css' %}" />
</head>

<body>
    <div id="main-wrapper">
        <div class="nav-header">
            <a href=" {% url 'frontend:index' %} " class="brand-logo justify-content-center">
                PSYCHOLOGY
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="dashboard_bar">
                                {% if head_title %}{{head_title}}{% else %}Dashboard{% endif %}
                            </div>
                        </div>
                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="javascript:;" role="button" data-toggle="dropdown">
                                    {% if request.user.profile_pic %}
                                    <img src="{{request.user.profile_pic.url}}" width="20" alt="" />
                                    {% else %}
                                    <img src="{% static 'admin-asset/images/dp.png' %} " width="20" alt="" />
                                    {% endif %}
                                    <div class="header-info">
                                        <span>Hello,<strong> {{ request.user.username }}</strong></span>
                                    </div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{% url 'accounts:view_user' request.user.id %}"
                                        class="dropdown-item ai-icon">
                                        <span id="icon-user1" class="far fa-user"></span>
                                        <span class="ml-2">Profile </span>
                                    </a>
                                    <a href="{% url 'accounts:Password_Change' %}" class="dropdown-item ai-icon">
                                        <span id="icon-logout" class="far fa-user-edit"></span>
                                        <span class="ml-1">Change Password</span>
                                    </a>
                                    <a href="{% url 'accounts:logout' %}" class="dropdown-item ai-icon">
                                        <span id="icon-logout" class="far fa-sign-out-alt"></span>
                                        <span class="ml-2">Logout </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="deznav">
            <div class="deznav-scroll">
                <ul class="metismenu" id="menu">
                    <li  {% if not head_title %}class="mm-active"{% endif %}>
                        <a href="{% url 'frontend:index' %}" aria-expanded="false">
                            <i class="fas fa-tachometer-alt"></i>
                            <span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li {% if head_title == "Services Management" %}class="mm-active"{% endif %}>
                        <a href="{% url 'services:services_list' %}">
                            <i class="far fa-ballot-check"></i>
                            <span class="nav-text ml-1">Services</span>
                        </a>
                    </li>
                    <li {% if head_title == "Contacts Management" %}class="mm-active"{% endif %}>
                        <a href="{% url 'contact:contacts_list' %}">
                            <i class="fas fa-address-book"></i>
                            <span class="nav-text ml-1">Contacts</span>
                        </a>
                    </li>
                    <li {% if head_title == "Ratings and Reviews" %}class="mm-active"{% endif %}>
                        <a href="{% url 'ratings:ratings_list' %}">
                            <i class="fas fa-star-half-alt"></i>
                            <span class="nav-text ml-1">Reviews</span>
                        </a>
                    </li>
                    <li {% if head_title == "Pages" or head_title == "Backup" or head_title == "Login History" %}class="mm-active"{% endif %}>
                        <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="fas fa-cogs"></i>
                            <span class="nav-text">Settings</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'page:page_list' %} ">Pages</a></li>
                            <li><a href="{% url 'backup:backup' %} ">Backup</a></li>
                            <li><a href="{% url 'accounts:login_history' %} ">Login History</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <script src="{% static 'admin-asset/js/moment.min.js' %}"></script>
        <script>
            function ConvertGTime(createdate, createtime) {
                d = createdate + "T" + createtime + "Z";
                const date = d;
                const local = moment.utc(date).local().format("lll");
                return local;
            }
        </script>
        {% if messages %}
            <div class="flash animate--drop-in-fade-out">
            {% for message in messages %}
                <div class="flash__icon">
                    <i class="icon far fa-check-circle"></i>
                </div>
                
                <p class="flash__body">
                    {{ message }}
                </p>
                {% endfor %}
            </div>
        {% endif %}