page/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'page'


urlpatterns = [
    url(r'^add-page/$', AddPage, name='add_page'),
    url(r'^pages/$', PagesView, name='page_list'),
    url(r'^delete-page/$', DeletePage, name='delete_page'),
    url(r'^view-page/(?P<id>[-\w]+)/$', ViewPage, name='view_page'),
    url(r'^edit-page/(?P<id>[-\w]+)/$', PageEdit, name='edit_page'),
    url(r'^change-state/(?P<id>[-\w]+)/$', ChangeState, name='change_state'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include, url
from django.conf import settings
from accounts.views import  AdminLoginView
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls', 'accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    path('backup/', include('backup.urls') , name="Back_up"),
    path('page/', include('page.urls') , name="page"),
    path('contacts/', include('contact.urls') , name="contact"),
    path('services/', include('services.urls') , name="services"),
    path('ratings/', include('ratings.urls') , name="ratings"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] 

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

services/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'services'


urlpatterns = [

    url(r'^$', ServicesList, name='services_list'),
    url(r'^add-service/$', AddService, name='add_service'),
    url(r'^delete-service/(?P<id>[-\w]+)/$', DeleteService, name='delete_service'),
    url(r'^view-service/(?P<id>[-\w]+)/$', ViewService, name='view_service'),
    url(r'^edit-service/(?P<id>[-\w]+)/$', EditService, name='edit_service'),
    
]

services/models.py
from django.db import models
from accounts.models import *


class Services(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='service_images/', blank=True, null=True)
    price = models.FloatField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, blank=True, null=True)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        managed = True;
        db_table = 'tbl_services'

services/views.py
from django.shortcuts import render, redirect
from accounts.constants import *
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def ServicesList(request):
	services = Services.objects.all().order_by('-id')
	if request.GET.get('id'):
		services = services.filter(id=request.GET.get('id'))
	if request.GET.get('title'):
		services = services.filter(title__icontains=request.GET.get('title'))
	if request.GET.get('description'):
		services = services.filter(description__icontains=request.GET.get('description'))
	if request.GET.get('price'):
		services = services.filter(price__icontains=request.GET.get('price'))
	if request.GET.get('created_on'):
		services = services.filter(created_on__date=request.GET.get('created_on'))
	page = request.GET.get('page', 1)
	paginator = Paginator(services, PAGE_SIZE)
	try:
		services = paginator.page(page)
	except PageNotAnInteger:
		services = paginator.page(1)
	except EmptyPage:
		services = paginator.page(paginator.num_pages)
	return render(request,'services/service-list.html',{"head_title":"Services Management","services":services,"id":request.GET.get('id'),"title":request.GET.get('title'),"description":request.GET.get('description'),"price":request.GET.get('price'),"created_on":request.GET.get('created_on')})


@login_required
def AddService(request):
    if request.method == 'POST':
        if Services.objects.filter(title=request.POST.get('title')):
            messages.error(request, "Service Title Already Exist!")
            return render(request, 'services/add-service.html',{"head_title":"Services Management"})
        else:
            service = Services.objects.create(
                title = request.POST.get('title'),
                description = request.POST.get('description'),
                image = request.FILES.get('image'),
                price = request.POST.get('price'),
                created_by = request.user,
            )
            messages.success(request,'Service Added Successfully!')
            return redirect('services:view_service',id=service.id)
    return render(request, 'services/add-service.html',{"head_title":"Services Management"})


@login_required
def DeleteService(request,id):
    service = Services.objects.get(id=id).delete()
    messages.success(request,'Service Deleted Successfully!')
    return redirect('services:services_list')


@login_required
def ViewService(request,id):
    service = Services.objects.get(id=id)
    return render(request, 'services/view-service.html',{"head_title":"Services Management","service":service})


@login_required
def EditService(request, id):
    service = Services.objects.get(id=id)
    if request.method == 'POST':
        service_exist = Services.objects.filter(title=request.POST.get('title')).exclude(id=id)
        if service_exist:
            messages.error(request, "Service Title Already Exist!")
            return render(request, 'services/edit-service.html',{"head_title":"Services Management","service":service})
        else:
            service.title = request.POST.get('title')
            service.description = request.POST.get('description')
            if request.FILES.get('image'):
                service.image = request.FILES.get('image')
            service.price = request.POST.get('price')
            service.save()
            messages.success(request,'Service Updated Successfully!')
            return redirect('services:view_service',id=service.id)
    return render(request, 'services/edit-service.html',{"head_title":"Services Management","service":service})

templates/services/add-service.html
{% include 'admin-includes/header.html' %} {% load static %} {% block content %}


<div class="content-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h4 class="card-title">Add Service</h4>
                    </div>
                    <div class="card-body">
                        <div class="profile-tab">
                            <div class="settings-form">
                                <form id="add-service" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label>Service Title</label>
                                            <input id="title" type="text" placeholder="Enter Service Title"  name="title" class="form-control form-control-lg" maxlength="254">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Service Image</label>
                                            <input type="file" name="image" class="form-control form-control-lg">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Service Price</label>
                                            <input type="text" maxlength="7" onkeypress="return /[0-9.]/i.test(event.key)" name="price" placeholder="Enter Service Price" class="form-control form-control-lg">
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Service Description</label>
                                            <textarea placeholder="Enter Service Description" name="description" class="form-control form-control-lg" rows="4"></textarea>
                                        </div>
                                        <div class="form-group col-md-12">
                                            <button class="btn btn-primary" type="submit">Save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %} {% endblock %}
<script type="text/javascript">
    jQuery.validator.addMethod("dollarsscents", function (value, element) {
        return this.optional(element) || /^\d{0,20}(\.\d{0,2})?$/i.test(value);
    }, "You must include two decimal places");
    $("#add-service").validate({
        rules: {
            price: {
                required: true,
                number: true,
                min: 1,
                dollarsscents: true,
            },
            title: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            description: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            image: {
                accept: "jpg,png,jpeg,gif",
                required: true,
            }
        },
        messages: {
            price: {
                required: "Please enter service price",
            },
            title: {
                required: "Please enter title",
            },
            description: {
                required: "Please enter description"
            },
            image: {
                accept: "Please upload file in these format only (jpg, jpeg, png, gif)",
                required: "Please select a image",
            }
        }
    });
</script>

templates/services/edit-service.html
{% include 'admin-includes/header.html' %} {% load static %} {% block content %}


<div class="content-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h4 class="card-title">Edit Service</h4>
                    </div>
                    <div class="card-body">
                        <div class="profile-tab">
                            <div class="settings-form">
                                <form id="add-service" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label>Service Title</label>
                                            <input id="title" type="text" placeholder="Enter Service Title"  name="title" value={{service.title}} class="form-control form-control-lg" maxlength="254">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Service Image</label>
                                            <input type="file" name="image" class="form-control form-control-lg">
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Service Price</label>
                                            <input value="{{service.price|floatformat:2}}" type="text" maxlength="7" onkeypress="return /[0-9.]/i.test(event.key)" name="price" placeholder="Enter Service Price" class="form-control form-control-lg">
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Service Description</label>
                                            <textarea placeholder="Enter Service Description" name="description" class="form-control form-control-lg" rows="4">{{service.description}}</textarea>
                                        </div>
                                        <div class="form-group col-md-12">
                                            <button class="btn btn-primary" type="submit">Save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %} {% endblock %}
<script type="text/javascript">
    jQuery.validator.addMethod("dollarsscents", function (value, element) {
        return this.optional(element) || /^\d{0,20}(\.\d{0,2})?$/i.test(value);
    }, "You must include two decimal places");
    $("#add-service").validate({
        rules: {
            price: {
                required: true,
                number: true,
                min: 1,
                dollarsscents: true,
            },
            title: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            description: {
                required: true,
                normalizer: function( value ) {
                    return $.trim( value );
                }
            },
            image: {
                accept: "jpg,png,jpeg,gif",
            }
        },
        messages: {
            price: {
                required: "Please enter service price",
            },
            title: {
                required: "Please enter title",
            },
            description: {
                required: "Please enter description"
            },
            image: {
                accept: "Please upload file in these format only (jpg, jpeg, png, gif)",
            }
        }
    });
</script>

templates/services/service-list.html
{% include 'admin-includes/header.html' %}
{% load static %}
{% block content %}		

<div class="content-body">
    <!-- row -->
    <div class="container-fluid">	
        <div class="row">
            <div class="col-12">
                <div class="card card-custom">
                    <div class="card-header d-flex justify-content-between align-items-center card-header-custom">
                        <h4 class="card-title">Services Management</h4>
                        <div class="addlocation">
                            <a href="{% url 'services:add_service' %}">Add<i class="far fa-plus ml-1"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form action="{% url 'services:services_list' %}" method="GET">
                                <table class="sortable table table-responsive-md ">
                                    <thead>
                                        <tr>
                                            <th><strong>Id</strong></th>
                                            <th><strong>Title</strong></th>
                                            <th><strong>Description</strong></th>
                                            <th><strong>Price</strong></th>
                                            <th><strong>Created On</strong></th>
                                            <th><strong>Action</strong></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><input style="width: 70px;" type="text" {% if id %}value="{{id}}" {% endif %} class="form-control" name="id"></td>
                                            <td><input type="text" {% if title %} value="{{title}}" {% endif %} class="form-control" name="title"></td>
                                            <td><input type="text" {% if description %} value="{{description}}" {% endif %} class="form-control" name="description"></td>
                                            <td><input type="text" {% if price %} value="{{price}}" {% endif %} class="form-control" name="price"></td>
                                            <td><input onchange="this.form.submit()" type="date" onkeydown="return false" value="{{created_on}}" class="position-relative form-control" name="created_on"></td>
                                            <td><button type="submit" class="btn btn-dark savebtn">Search</button></td>
                                        </tr>
                                    {% if services %}
                                        {% for service in services  %}
                                            <tr>
                                                <td>{{service.id}}</td>
                                                <td>{{service.title}}</td>
                                                <td>{{service.description | truncatechars:80 |safe}}</td>
                                                <td>₹{{service.price|floatformat:2}}</td>
                                                <td>
                                                    <script>
                                                        var d = ConvertGTime("{{ service.created_on|date:'Y-m-d' }}","{{ service.created_on|time:'H:i' }}");
                                                        document.write(d);
                                                    </script>
                                                </td>
                                                <td>
                                                    <div class="d-flex">
                                                        <a href="{% url 'services:edit_service' service.id %}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-pencil"></i></a>
                                                        <a href="{% url 'services:view_service' service.id %}" class="btn btn-success shadow btn-xs sharp mr-1"><i class="fa fa-eye"></i></a>
                                                        <a onclick="return confirm('Are you sure to delete this service?')" href="{% url 'services:delete_service' service.id %}" class="btn btn-danger shadow btn-xs sharp"><i class="fa fa-trash"></i></a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <td align="center" colspan="6">No Data Found</td>
                                    {% endif %}
                                    </tbody>
                                </table>
                            </form>
                            {% if services.has_other_services %}
							<ul class="pagination">
								{% if services.has_previous %}
								<li><a href="?page={{ services.previous_page_number }}">&laquo;</a></li>
								{% else %}
								<li class="disabled"><span>&laquo;</span></li>
								{% endif %}
								{% for i in services.paginator.page_range %}
								{% if services.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% else %}
								<li><a href="?page={{ i }}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if services.has_next %}
								<li><a href="?page={{ services.next_page_number }}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span>&raquo;</span></li>
								{% endif %}
							</ul>
							{% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% include 'admin-includes/footer.html' %}
<script>
    $(document).on('click', '#delete-btn', function () {
        if (confirm("Are you sure to delete this page?")) {
            var id = $(this).attr('data-attr');
            $.ajax({
                url: "{% url 'page:delete_page' %}",
                type: 'get',
                data: {
                    'id': id
                },
                success: function (result) {
                    location.reload();
                }
            });
        }
    });
</script>

templates/services/view-service.html
{% include "admin-includes/header.html" %}
{% block content %}
{% load static %}
{% load humanize %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="text-right float-md-right">
                            <div class="addlocation mb-3">
                            </div>
                        </div>
                        <div class="profile-tab d-flex position-relative">
                            <div class="profile-imgbox mx-auto mx-md-0 mr-md-4">
                                {% if service.image %}
                                <img src="{{ service.image.url }}" alt="image">
                                {% endif %}
                            </div>
                            <div class="profile-personal-info w-100">
                                <h4 class="text-primary mb-4">Service Information</h4>
                                <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                        <h5 class="f-w-500">Title <span class="d-none d-sm-block float-sm-right">:</span>
                                        </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9"><span>{{service.title}}</span>
                                    </div>
                                </div>
                                <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                        <h5 class="f-w-500">Price <span class="d-none d-sm-block float-sm-right">:</span>
                                        </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9"><span>₹{{service.price|floatformat:2}}</span>
                                    </div>
                                </div>
                                <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                        <h5 class="f-w-500">Description <span class="d-none d-sm-block float-sm-right">:</span>
                                        </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9"><span>{{service.description}}</span>
                                    </div>
                                </div>
                                <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                        <h5 class="f-w-500">Created On <span class="d-none d-sm-block float-sm-right">:</span>
                                        </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9">
                                        <script>
                                            var d = ConvertGTime("{{ service.created_on|date:'Y-m-d' }}","{{ service.created_on|time:'H:i' }}");
                                            document.write(d);
                                        </script>
                                    </div>
                                </div>
                                <div class="row mb-3 mb-sm-2">
                                    <div class="col-12 col-sm-4 col-lg-3">
                                        <h5 class="f-w-500">Updated On <span class="d-none d-sm-block float-sm-right">:</span>
                                        </h5>
                                    </div>
                                    <div class="col-12 col-sm-8 col-lg-9">
                                        <script>
                                            var d = ConvertGTime("{{ service.updated_on|date:'Y-m-d' }}","{{ service.updated_on|time:'H:i' }}");
                                            document.write(d);
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}
{% include "admin-includes/footer.html" %}