accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

admin.autodiscover()

app_name = 'accounts'

urlpatterns = [
    ## Admin
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^edit-user/(?P<id>[-\w]+)/$', EditUser, name='edit_user'),
    url(r'^view/(?P<id>[-\w]+)/$',ViewUser, name='view_user'),
    url(r'^change-password/$', PasswordChange.as_view(), name='Password_Change'),

    ## Login History
    url(r'^login-history/$', LoginHistoryView, name='login_history'),
    url(r'^delete-history/$', DeleteHistory, name='delete_history'),
]

contact/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'contact'


urlpatterns = [
    url(r'^$', ContactsList, name='contacts_list'),
    url(r'^contacts-graph$', ContactsGraph, name='contacts_graph'),
    url(r'^contact-us/$', ContactFormView, name='contact_form'),
    url(r'^delete-contact/(?P<id>[-\w]+)/$', DeleteContact, name='delete_contact'),
    url(r'^view-contact/(?P<id>[-\w]+)/$', ViewContact, name='view_contact'),
]

frontend/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *
from .sitemaps import *
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

app_name = 'frontend'

sitemaps = {
    'pages': StaticSitemap,
}

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about-us/$', AboutUs, name='abouts'),
    url(r'^privacy-policy/$', PrivacyPolicy, name='privacy_policy'),
    url(r'^terms-and-conditions/$', TermsAndConditions, name='terms_and_conditions'),
    url(r'^sitemap.xml/$', sitemap, {'sitemaps': sitemaps}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'page'


urlpatterns = [
    url(r'^add-page/$', AddPage, name='add_page'),
    url(r'^pages/$', PagesView, name='page_list'),
    url(r'^delete-page/$', DeletePage, name='delete_page'),
    url(r'^view-page/(?P<id>[-\w]+)/$', ViewPage, name='view_page'),
    url(r'^edit-page/(?P<id>[-\w]+)/$', PageEdit, name='edit_page'),
    url(r'^change-state/(?P<id>[-\w]+)/$', ChangeState, name='change_state'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import include, url
from django.conf import settings
from accounts.views import  AdminLoginView
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/login/', AdminLoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls', 'accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    path('backup/', include('backup.urls') , name="Back_up"),
    path('page/', include('page.urls') , name="page"),
    path('contacts/', include('contact.urls') , name="contact"),
    path('services/', include('services.urls') , name="services"),
    path('ratings/', include('ratings.urls') , name="ratings"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] 

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

ratings/urls.py
from .views import *
from django.conf.urls import url
from django.contrib import admin


admin.autodiscover()
app_name = 'ratings'


urlpatterns = [
    url(r'^$', RatingReviewsList, name='ratings_list'),
    url(r'^rate-our-services/$', RateUsForm, name='rate_us'),
    url(r'^delete-review/(?P<id>[-\w]+)/$', DeleteReview, name='delete_review'),
    url(r'^view-review/(?P<id>[-\w]+)/$', ViewReview, name='view_review'),
]

frontend/views.py
from django.shortcuts import render,redirect
from accounts.constants import *
from page.models import *
from services.models import *
from ratings.models import *
import logging
db_logger = logging.getLogger('db')


## Index Page
def index(request):
    if request.user.is_authenticated == True and request.user.is_superuser and request.user.role_id == ADMIN:
        return redirect('admin:index')
    else:
        services = Services.objects.all().order_by('-id')
        reviews = RatingReviews.objects.all().order_by('-id')
        return render(request, "frontend/index.html",{"services":services, "reviews":reviews})


## About Us Page 
def TermsAndConditions(request):
    try:
        content = Pages.objects.get(type_id=TERMS_AND_CONDITION)
    except:
        content = None
    return render(request, "frontend/staticpage.html",{"content":content, "title":"TERMS & CONDITIONS"})


## About Us Page 
def AboutUs(request):
    try:
        content = Pages.objects.get(type_id=ABOUT_US)
    except:
        content = None
    return render(request, "frontend/staticpage.html",{"content":content, "title":"ABOUT US"})


## Privacy Page 
def PrivacyPolicy(request):
    try:
        content = Pages.objects.get(type_id=PRIVACY_POLITY)
    except:
        content = None
    return render(request, "frontend/staticpage.html",{"content":content, "title":"PRIVACY POLICY"})


def handler404(request, exception, template_name="frontend/404.html"):
    db_logger.exception(Exception)
    return render(request, template_name, status=404)
    

def handler500(request, *args, **argv):
    db_logger.exception(Exception)
    return render(request, 'frontend/404.html', status=500)
    

def handler403(request, exception, template_name="frontend/404.html"):
    db_logger.exception(exception)
    return render(request, template_name, status=403)
    

def handler400(request, exception, template_name="frontend/404.html"):
    db_logger.exception(exception)
    return render(request, template_name, status=400)
    

templates/frontend/includes/footer.html
{% load static %}
</main>
<!--Footer Here-->
<footer class="footer">
    <div class="container">
        <ul class="social-link text-center">
            <li><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="" target="_blank"><i class="fab fa-twitter"></i></a></li>
        </ul>
    </div>
</footer>
<div class="footer-bottom text-center">
    <div class="container">
        <p>
            <a target="_blank" href="{% url 'frontend:privacy_policy' %}" title="Privacy Policy">Privacy Policy</a> | 
            &copy; <script>document.write(new Date().getFullYear());</script> Psychology
        </p>
    </div>
</div>
<!-- common -->
<script src="{% static 'admin-asset/js/jquery.min.js' %}"></script>
<script src="{% static 'frontend-asset/js/common.js' %}"></script>
<script src="{% static 'admin-asset/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'admin-asset/js/additional-methods.min.js' %}"></script>
<!-- SCRIPTS -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/aos.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/smoothscroll.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>

</body>

</html>

templates/frontend/includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Psychology</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="" />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
    <link
        rel="stylesheet"
        href="{% static 'frontend-asset/css/helpers-plugin.css' %}"
    />
    <link
        rel="stylesheet"
        href="{% static 'frontend-asset/fonts/fontawesome/css/all.min.css' %}"
    />
    <link
        rel="stylesheet"
        href="{% static 'frontend-asset/css/flash.css' %}"
    />
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-digital-trend.css' %}">
</head>
<body>
    <!-- MENU BAR -->
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'frontend:index' %}">
              PSYCHOLOGY
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'frontend:abouts' %}" class="nav-link smoothScroll">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'contact:contact_form' %}" class="nav-link smoothScroll">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'ratings:rate_us' %}" class="nav-link smoothScroll">Rate Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:login' %}" class="nav-link smoothScroll">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="page-wrapper">
        {% if messages %}
        <div class="flash animate--drop-in-fade-out">
            {% for message in messages %}
            <div class="flash__icon">
                <i class="icon far fa-check-circle"></i>
            </div>

            <p class="flash__body">{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
    </main>